name: Build on PR

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: |
          for file in src/*/*.sln
          do
            dotnet restore "$file"
          done
  
      - name: Build solutions
        run: |
          for file in src/*/*.sln
          do
            dotnet build "$file"
          done
      - name: Run tests
        run: |
          for file in src/*/*.sln
          do
            dotnet test "$file"
          done
